"""Daily trading-analysis report — write docs/analysis/<date>.md.

Usage:
    uv run python scripts/daily_analysis.py                 # today (IST)
    uv run python scripts/daily_analysis.py --date 2026-08-05
    uv run python scripts/daily_analysis.py --week-of 2026-08-03   # + weekly roll-up
    uv run python scripts/daily_analysis.py --date 2026-08-05 --user 1

Read-only against the DB. Produces:
  - docs/analysis/<YYYY-MM-DD>.md   the day's report
  - docs/analysis/LEDGER.md         one running line per day (the improvement log)
  - docs/analysis/WEEK-<monday>.md  when --week-of is given

Everything the report needs is derived from durable data (signals,
signal_outcomes, positions/orders, 1m candles). See
app/services/daily_report.py.
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import sys
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal
from pathlib import Path

# Runnable from any cwd: put backend/ (the `app` package root) on sys.path.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.db.session import AsyncSessionFactory  # noqa: E402
from app.services.daily_report import (  # noqa: E402
    DailyReport,
    build_daily_report,
    build_week_summary,
    render_markdown,
    render_week_markdown,
)

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_ANALYSIS_DIR = _REPO_ROOT / "docs" / "analysis"

_LEDGER_HEADER = [
    "# Daily analysis ledger",
    "",
    "One line per trading day — the running record so improvement (or its "
    "absence) is visible at a glance and drives the fine-tuning. Newest first. "
    "Generated by `scripts/daily_analysis.py`; edit the dated reports, not this "
    "table.",
    "",
    "| Date | Entries | Exits | Realised (net) | Open MTM | Given back "
    "| Reached ≥1R | Chased | Heat % | Report |",
    "|---|---:|---:|---:|---:|---:|---:|---:|---:|---|",
]


def _signed(x: Decimal) -> str:
    return f"+₹{x:,.0f}" if x >= 0 else f"−₹{abs(x):,.0f}"


def _ledger_row(r: DailyReport) -> tuple[str, str]:
    with_exc = [t for t in r.opened if t.excursion is not None]
    reached = sum(1 for t in with_exc if t.excursion and t.excursion.reached_1r)
    chased = sum(1 for t in r.opened if t.chase is not None and t.chase.past_chase_ceiling)
    heat = (
        (r.open_risk_total / Decimal(str(r.user.capital_inr)) * 100)
        if r.user.capital_inr
        else Decimal(0)
    )
    key = r.day.isoformat()
    row = (
        f"| {key} | {len(r.opened)} | {len(r.closed)} | {_signed(r.realized_today)} "
        f"| {_signed(r.open_unrealized_eod)} | {_signed(-r.given_back_total)} "
        f"| {reached}/{len(with_exc)} | {chased} | {heat:.1f}% | [{key}]({key}.md) |"
    )
    return key, row


def _update_ledger(r: DailyReport) -> None:
    ledger = _ANALYSIS_DIR / "LEDGER.md"
    rows: dict[str, str] = {}
    if ledger.exists():
        for line in ledger.read_text().splitlines():
            s = line.strip()
            if s.startswith("| 20") and "|" in s[1:]:
                key = s.split("|")[1].strip()
                rows[key] = line
    key, row = _ledger_row(r)
    rows[key] = row
    ordered = [rows[k] for k in sorted(rows, reverse=True)]
    ledger.write_text("\n".join([*_LEDGER_HEADER, *ordered, ""]))


async def _run(day: date, user_id: int, week_of: date | None, now: datetime) -> int:
    # The app engine enables echo at import and re-arms it on lazy connect, so a
    # per-logger level doesn't stick. This is a read-only CLI, so disable INFO
    # and below globally — stdout is then just the "wrote …" lines.
    logging.disable(logging.INFO)
    _ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

    async with AsyncSessionFactory() as db:
        report = await build_daily_report(db, day=day, user_id=user_id, now=now)
        path = _ANALYSIS_DIR / f"{day.isoformat()}.md"
        path.write_text(render_markdown(report))
        _update_ledger(report)
        print(f"wrote {path.relative_to(_REPO_ROOT)}", flush=True)

        # Regime-gate forward evidence (Phase 6): what the shadow overlay WOULD
        # suppress on the live tradeable cohort, written every session so the flip
        # decision accrues on live evidence, with a readiness banner (the passive
        # reminder printed below). Read-only; guarded so it can never block the
        # primary daily report — a failure prints a visible line, not a silent skip.
        try:
            from app.services import regime_gate_shadow as rgs

            shadow = await rgs.compute_regime_gate_shadow(db)
            spath = _ANALYSIS_DIR / f"regime-gate-shadow-{day.isoformat()}.md"
            spath.write_text(rgs.render_markdown(shadow, day=day))
            print(f"wrote {spath.relative_to(_REPO_ROOT)}", flush=True)
            print(rgs.readiness_line(shadow), flush=True)
        except Exception as exc:  # noqa: BLE001 - never block the daily report; surface, don't swallow
            print(f"regime-gate shadow step skipped: {exc!r}", flush=True)

        # Circuit-gate forward evidence (Phase 6.8.3): what the circuit overlay
        # WOULD suppress on the live paper-entry cohort (entries near the adverse
        # band), with a readiness banner. Same read-only, never-block discipline as
        # the regime-gate sidecar above.
        try:
            from app.services import circuit_gate_shadow as cgs

            cshadow = await cgs.compute_circuit_gate_shadow(db)
            cpath = _ANALYSIS_DIR / f"circuit-gate-shadow-{day.isoformat()}.md"
            cpath.write_text(cgs.render_markdown(cshadow, day=day))
            print(f"wrote {cpath.relative_to(_REPO_ROOT)}", flush=True)
            print(cgs.readiness_line(cshadow), flush=True)
        except Exception as exc:  # noqa: BLE001 - never block the daily report; surface, don't swallow
            print(f"circuit-gate shadow step skipped: {exc!r}", flush=True)

        # Entry-quality forward evidence (6.8 R-track): what the breadth (diversity,
        # ACTIVE) + stop-tightness (sl_atr, SHADOW) checks flag on the live signal
        # cohort, with flagged-vs-passed outcomes + an sl_atr flip-readiness banner.
        # Same read-only, never-block discipline as the gate sidecars above.
        try:
            from app.services import entry_quality_shadow as eqs

            eshadow = await eqs.compute_entry_quality_shadow(db)
            epath = _ANALYSIS_DIR / f"entry-quality-shadow-{day.isoformat()}.md"
            epath.write_text(eqs.render_markdown(eshadow, day=day))
            print(f"wrote {epath.relative_to(_REPO_ROOT)}", flush=True)
            print(eqs.readiness_line(eshadow), flush=True)
        except Exception as exc:  # noqa: BLE001 - never block the daily report; surface, don't swallow
            print(f"entry-quality shadow step skipped: {exc!r}", flush=True)

        # Sector/index relative-strength forward evidence (MCE slice 3): what the RS
        # overlay WOULD suppress on the live signal cohort (stocks under-performing their
        # benchmark index), with a per-entry context table + a flip-readiness banner —
        # the MCE requirement to never trade blind to sector leadership. Same read-only,
        # never-block discipline as the gate sidecars above.
        try:
            from app.services import sector_rs_shadow as srs

            rshadow = await srs.compute_sector_rs_shadow(db)
            rpath = _ANALYSIS_DIR / f"sector-rs-shadow-{day.isoformat()}.md"
            rpath.write_text(srs.render_markdown(rshadow, day=day))
            print(f"wrote {rpath.relative_to(_REPO_ROOT)}", flush=True)
            print(srs.readiness_line(rshadow), flush=True)
        except Exception as exc:  # noqa: BLE001 - never block the daily report; surface, don't swallow
            print(f"sector-RS shadow step skipped: {exc!r}", flush=True)

        if week_of is not None:
            monday = week_of - timedelta(days=week_of.weekday())
            wk = await build_week_summary(db, monday=monday, user_id=user_id, now=now)
            wpath = _ANALYSIS_DIR / f"WEEK-{monday.isoformat()}.md"
            wpath.write_text(render_week_markdown(wk))
            print(f"wrote {wpath.relative_to(_REPO_ROOT)}", flush=True)
    return 0


def main() -> None:
    ap = argparse.ArgumentParser(description="Daily trading-analysis report")
    ap.add_argument(
        "--date", type=str, default=None, help="IST day YYYY-MM-DD (default: today IST)"
    )
    ap.add_argument("--user", type=int, default=1, help="user id (default: 1)")
    ap.add_argument(
        "--week-of",
        type=str,
        default=None,
        help="also emit the Mon–Fri weekly roll-up covering this YYYY-MM-DD",
    )
    args = ap.parse_args()

    from zoneinfo import ZoneInfo

    now = datetime.now(tz=UTC)
    ist_today = now.astimezone(ZoneInfo("Asia/Kolkata")).date()
    day = date.fromisoformat(args.date) if args.date else ist_today
    week_of = date.fromisoformat(args.week_of) if args.week_of else None
    raise SystemExit(asyncio.run(_run(day, args.user, week_of, now)))


if __name__ == "__main__":
    main()
