"""Daily trading-analysis report — write docs/analysis/<date>.md.

Usage:
    uv run python scripts/daily_analysis.py                 # today (IST)
    uv run python scripts/daily_analysis.py --date 2026-08-05
    uv run python scripts/daily_analysis.py --week-of 2026-08-03   # + weekly roll-up
    uv run python scripts/daily_analysis.py --date 2026-08-05 --user 1

Read-only against the DB. Produces:
  - docs/analysis/<YYYY-MM-DD>.md   the day's report
  - docs/analysis/LEDGER.md         one running line per day (the improvement log)
  - docs/analysis/WEEK-<monday>.md  when --week-of is given

Everything the report needs is derived from durable data (signals,
signal_outcomes, positions/orders, 1m candles). See
app/services/daily_report.py.
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import sys
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal
from pathlib import Path

# Runnable from any cwd: put backend/ (the `app` package root) on sys.path.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.db.session import AsyncSessionFactory  # noqa: E402
from app.services.daily_report import (  # noqa: E402
    DailyReport,
    build_daily_report,
    build_week_summary,
    render_markdown,
    render_week_markdown,
)

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_ANALYSIS_DIR = _REPO_ROOT / "docs" / "analysis"

_LEDGER_HEADER = [
    "# Daily analysis ledger",
    "",
    "One line per trading day — the running record so improvement (or its "
    "absence) is visible at a glance and drives the fine-tuning. Newest first. "
    "Generated by `scripts/daily_analysis.py`; edit the dated reports, not this "
    "table.",
    "",
    "| Date | Entries | Exits | Realised (net) | Open MTM | Given back "
    "| Reached ≥1R | Chased | Heat % | Report |",
    "|---|---:|---:|---:|---:|---:|---:|---:|---:|---|",
]


def _signed(x: Decimal) -> str:
    return f"+₹{x:,.0f}" if x >= 0 else f"−₹{abs(x):,.0f}"


def _ledger_row(r: DailyReport) -> tuple[str, str]:
    with_exc = [t for t in r.opened if t.excursion is not None]
    reached = sum(1 for t in with_exc if t.excursion and t.excursion.reached_1r)
    chased = sum(1 for t in r.opened if t.chase is not None and t.chase.past_chase_ceiling)
    heat = (
        (r.open_risk_total / Decimal(str(r.user.capital_inr)) * 100)
        if r.user.capital_inr
        else Decimal(0)
    )
    key = r.day.isoformat()
    row = (
        f"| {key} | {len(r.opened)} | {len(r.closed)} | {_signed(r.realized_today)} "
        f"| {_signed(r.open_unrealized_eod)} | {_signed(-r.given_back_total)} "
        f"| {reached}/{len(with_exc)} | {chased} | {heat:.1f}% | [{key}]({key}.md) |"
    )
    return key, row


def _update_ledger(r: DailyReport) -> None:
    ledger = _ANALYSIS_DIR / "LEDGER.md"
    rows: dict[str, str] = {}
    if ledger.exists():
        for line in ledger.read_text().splitlines():
            s = line.strip()
            if s.startswith("| 20") and "|" in s[1:]:
                key = s.split("|")[1].strip()
                rows[key] = line
    key, row = _ledger_row(r)
    rows[key] = row
    ordered = [rows[k] for k in sorted(rows, reverse=True)]
    ledger.write_text("\n".join([*_LEDGER_HEADER, *ordered, ""]))


async def _run(day: date, user_id: int, week_of: date | None, now: datetime) -> int:
    # The app engine enables echo at import and re-arms it on lazy connect, so a
    # per-logger level doesn't stick. This is a read-only CLI, so disable INFO
    # and below globally — stdout is then just the "wrote …" lines.
    logging.disable(logging.INFO)
    _ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

    async with AsyncSessionFactory() as db:
        report = await build_daily_report(db, day=day, user_id=user_id, now=now)
        path = _ANALYSIS_DIR / f"{day.isoformat()}.md"
        path.write_text(render_markdown(report))
        _update_ledger(report)
        print(f"wrote {path.relative_to(_REPO_ROOT)}", flush=True)

        if week_of is not None:
            monday = week_of - timedelta(days=week_of.weekday())
            wk = await build_week_summary(db, monday=monday, user_id=user_id, now=now)
            wpath = _ANALYSIS_DIR / f"WEEK-{monday.isoformat()}.md"
            wpath.write_text(render_week_markdown(wk))
            print(f"wrote {wpath.relative_to(_REPO_ROOT)}", flush=True)
    return 0


def main() -> None:
    ap = argparse.ArgumentParser(description="Daily trading-analysis report")
    ap.add_argument(
        "--date", type=str, default=None, help="IST day YYYY-MM-DD (default: today IST)"
    )
    ap.add_argument("--user", type=int, default=1, help="user id (default: 1)")
    ap.add_argument(
        "--week-of",
        type=str,
        default=None,
        help="also emit the Mon–Fri weekly roll-up covering this YYYY-MM-DD",
    )
    args = ap.parse_args()

    from zoneinfo import ZoneInfo

    now = datetime.now(tz=UTC)
    ist_today = now.astimezone(ZoneInfo("Asia/Kolkata")).date()
    day = date.fromisoformat(args.date) if args.date else ist_today
    week_of = date.fromisoformat(args.week_of) if args.week_of else None
    raise SystemExit(asyncio.run(_run(day, args.user, week_of, now)))


if __name__ == "__main__":
    main()
